# -*- coding: utf-8 -*-
import os
import json
import logging
from typing import Dict, List, Any, Optional

class WorldStateManager:
    """
    World State Machine (WSM) Manager
    Responsible for tracking long-term state including inventory, health, relationships, and world flags.
    Ensures consistency across 100+ chapters.
    """
    
    STATE_FILENAME = "world_state.json"
    
    DEFAULT_STATE = {
        "meta": {
            "current_chapter": 0,
            "last_updated": "",
            "novel_version": "1.0"
        },
        "protagonist": {
            "name": "Unknown",
            "realm": "Mortal",
            "hp_status": "Healthy",
            "gold": 0,
            "inventory": [],  # List of strings or dicts
            "buffs": [],      # Active effects
            "skills": []      # Learned abilities
        },
        "relationships": {
            # "Name": {"affinity": 50, "status": "Neutral", "location": "Unknown"}
        },
        "world_flags": {
            # "event_name": True/False
        }
    }

    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.state_path = os.path.join(output_dir, self.STATE_FILENAME)
        self.state = self.load_state()

    def load_state(self) -> Dict:
        """Load state from JSON file or return default if not exists."""
        if os.path.exists(self.state_path):
            try:
                with open(self.state_path, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except Exception as e:
                logging.error(f"Failed to load world state: {e}")
                return self.DEFAULT_STATE.copy()
        return self.DEFAULT_STATE.copy()

    def save_state(self):
        """Save current state to JSON file."""
        try:
            with open(self.state_path, 'w', encoding='utf-8') as f:
                json.dump(self.state, f, indent=2, ensure_ascii=False)
            logging.info(f"World state saved to {self.state_path}")
        except Exception as e:
            logging.error(f"Failed to save world state: {e}")

    def initialize_state(self, architecture_content: str, protagonist_name: str):
        """
        Initialize state from novel architecture.
        Should be called when generating the first chapter or resetting.
        """
        self.state = self.DEFAULT_STATE.copy()
        self.state["protagonist"]["name"] = protagonist_name
        # Potential future enhancement: Parse architecture_content to extract initial state
        self.save_state()
        logging.info(f"World state initialized for protagonist: {protagonist_name}")

    def get_state_snapshot(self) -> str:
        """
        Generate a formatted string for Prompt Injection.
        """
        p = self.state.get("protagonist", {})
        
        # Format Inventory
        inventory = p.get("inventory", [])
        inv_str = ", ".join([i['name'] if isinstance(i, dict) else str(i) for i in inventory]) if inventory else "Empty"
        
        # Format Status
        hp_status = p.get("hp_status", "Healthy")
        buffs = ", ".join(p.get("buffs", [])) if p.get("buffs") else "None"
        realm = p.get("realm", "Unknown")
        
        snapshot = (
            f"【Current World State (STRICTLY CONSISTENT)】\n"
            f"- Protagonist: {p.get('name', 'Unknown')}\n"
            f"- Current Realm: {realm}\n"
            f"- Health Status: {hp_status}\n"
            f"- Active Buffs/Debuffs: {buffs}\n"
            f"- Inventory: {inv_str}\n"
            f"- World Context: {self._format_world_flags()}"
        )
        return snapshot

    def _format_world_flags(self) -> str:
        flags = self.state.get("world_flags", {})
        active_flags = [k for k, v in flags.items() if v]
        return ", ".join(active_flags) if active_flags else "Standard State"

    def apply_updates(self, updates: Dict):
        """
        Apply updates generated by the State Updater Agent.
        updates format expected:
        {
            "protagonist": {"hp_status": "...", "add_inventory": [...], "remove_inventory": [...]},
            "world_flags": {"new_flag": True}
        }
        """
        if not updates:
            return

        p_updates = updates.get("protagonist", {})
        
        # Update scalar fields
        if "realm" in p_updates:
            self.state["protagonist"]["realm"] = p_updates["realm"]
        if "hp_status" in p_updates:
            self.state["protagonist"]["hp_status"] = p_updates["hp_status"]
        if "gold_change" in p_updates:
            current_gold = self.state["protagonist"].get("gold", 0)
            self.state["protagonist"]["gold"] = current_gold + int(p_updates["gold_change"])
            
        # Update Inventory
        if "add_inventory" in p_updates:
            for item in p_updates["add_inventory"]:
                # Ensure simple string or dict structure
                self.state["protagonist"]["inventory"].append(item)
        
        if "remove_inventory" in p_updates:
             # Simple removal logic (by name)
             remove_list = p_updates["remove_inventory"]
             current_inv = self.state["protagonist"]["inventory"]
             new_inv = []
             for item in current_inv:
                 item_name = item['name'] if isinstance(item, dict) else str(item)
                 if item_name not in remove_list:
                     new_inv.append(item)
                 else:
                     remove_list.remove(item_name) # Remove one instance
             self.state["protagonist"]["inventory"] = new_inv

        # Update Flags
        w_updates = updates.get("world_flags", {})
        for k, v in w_updates.items():
            self.state["world_flags"][k] = v

        self.save_state()

    def update_state_from_chapter(self, chapter_content: str, llm_adapter):
        """
        Agentic State Update: Reads the chapter and updates the JSON state.
        """
        snapshot = self.get_state_snapshot()
        
        prompt = f"""You are the **World State Manager** database system.
Your job is to read the new chapter and output a JSON Patch to update the world state.

### Current World State
{snapshot}

### New Chapter Content
{chapter_content}

### Instructions
1. Analyze the chapter for any of the following changes:
   - **Health Change**: injuries, healing, poisoning, death.
   - **Inventory Change**: items obtained (loot, gift, buy) or lost (used, broken, sold).
   - **Realm Change**: breakthrough or regression in cultivation base.
   - **Wealth Change**: gold/spirit stones gained or spent.
   - **World Events**: key plot flags that should be permanently recorded (e.g. "Sect War Started").

2. **Strict Rules**:
   - Only output changes that EXPLICITLY happened in the text.
   - If no change, return empty JSON.
   - "Inventory" items should be specific nouns.
   - Return valid JSON only.

### Output values
Return a JSON object with ONLY the fields that need updating.
Format:
{{
    "protagonist": {{
        "hp_status": "new status string",
        "realm": "new realm string",
        "gold_change": +100 or -50,
        "add_inventory": ["Item Name 1", "Item Name 2"],
        "remove_inventory": ["Item Name Used"]
    }},
    "world_flags": {{
        "event_name": true
    }}
}}

### Output
JSON only:"""
        
        try:
            logging.info("State Updater Agent analyzing chapter...")
            response = llm_adapter.invoke(prompt)
            
            # Simple cleaning
            json_str = response.strip()
            if "```json" in json_str:
                json_str = json_str.split("```json")[1].split("```")[0]
            elif "```" in json_str:
                json_str = json_str.split("```")[1].split("```")[0]
            
            # Handle possible empty or non-JSON response
            if not json_str.strip():
                return
                
            updates = json.loads(json_str)
            logging.info(f"State Updates detected: {updates}")
            self.apply_updates(updates)
            
        except Exception as e:
            logging.error(f"State Update Agent failed: {e}")
            # Non-blocking error, just log it
